### ISSUE TITLE
Missing include - TimerInterrupt.h

### ISSUE THREAD

**Issue by bcarroll** [chmod775/SMARTResponseTerminal#1]
The Arduino sketch (.ino) file includes a local file, TimerInterrupt.h, but that file is not in the repo.

**Comment by itfloater** [comment]
> The Arduino sketch (.ino) file includes a local file, TimerInterrupt.h, but that file is not in the repo.

This is installed in the Arduino IDE
    https://www.arduino.cc/reference/en/libraries/timerinterrupt/

**Comment by itfloater** [comment]
Is your linux distro you use running u-boot or grub?  Trying to work out how to set the row and column values pre-boot so that overflow cursor move stops happening...

**Comment by bcarroll** [comment]
> > The Arduino sketch (.ino) file includes a local file, TimerInterrupt.h, but that file is not in the repo.
> 
> This is installed in the Arduino IDE
> https://www.arduino.cc/reference/en/libraries/timerinterrupt/

Perhaps missing documentation is the real issue here.  That TimerInterupt library is not installed by default in the Arduino IDE, it has to be manually added. After installing the library the code compiles successfully.

**Comment by chmod775** [comment]
Yes, to be precise I’ve used this library: https://github.com/khoih-prog/TimerInterrupt

Sorry for the documentation, I’m working on it with some schematics and images.
